### ISSUE TITLE
Can You modify this for Samsung M21 

### ISSUE THREAD

**Issue by Ajaythepower1606** [Team-420/KekHunter-420#2]
I am using Samsung Phone so many of my friends also need this because we are not able to do it .....
Please think about it .....

Great respect to you guys doing a great thing.

**Comment by Martinvlba** [comment]
I think its better if u join into this group and tell a bit more why and what will u use this rom for. Then maybe i can make a port of it for that device.

https://t.me/KekHunter

Its a support/chat group about this rom.
